#!/bin/bash

# Icon Generation Script for YarvixBrowser
# This script generates all required icon formats from the SVG source

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PROJECT_DIR/build"
ICONS_DIR="$BUILD_DIR/icons"
SVG_SOURCE="$BUILD_DIR/icon.svg"

echo "🎨 Generating icons for YarvixBrowser..."

# Check if source SVG exists
if [ ! -f "$SVG_SOURCE" ]; then
    echo "❌ Error: Source SVG not found at $SVG_SOURCE"
    exit 1
fi

# Create icons directory
mkdir -p "$ICONS_DIR"

# Check for required tools
if ! command -v sips &> /dev/null; then
    echo "❌ Error: sips not found (macOS required for icon generation)"
    exit 1
fi

# First, we need to convert SVG to PNG
# On macOS, we can use qlmanage or install librsvg via brew
if command -v rsvg-convert &> /dev/null; then
    CONVERTER="rsvg-convert"
elif command -v qlmanage &> /dev/null; then
    CONVERTER="qlmanage"
else
    echo "⚠️  No SVG converter found. Install librsvg: brew install librsvg"
    echo "   Or manually create build/icon.png (1024x1024)"

    # Create a placeholder message
    echo "Please create build/icon.png manually from the SVG, then run this script again."
    exit 1
fi

# Convert SVG to 1024x1024 PNG (master icon)
echo "📐 Converting SVG to PNG..."
if [ "$CONVERTER" = "rsvg-convert" ]; then
    rsvg-convert -w 1024 -h 1024 "$SVG_SOURCE" -o "$BUILD_DIR/icon.png"
elif [ "$CONVERTER" = "qlmanage" ]; then
    # qlmanage creates thumbnails - not ideal but works
    cd "$BUILD_DIR"
    qlmanage -t -s 1024 -o . icon.svg 2>/dev/null || true
    if [ -f "icon.svg.png" ]; then
        mv "icon.svg.png" "icon.png"
    fi
fi

# Check if PNG was created
if [ ! -f "$BUILD_DIR/icon.png" ]; then
    echo "❌ Could not create PNG from SVG"
    echo "   Please install librsvg: brew install librsvg"
    exit 1
fi

echo "✅ Created master PNG (1024x1024)"

# Generate Linux icon sizes
echo "🐧 Generating Linux icons..."
for SIZE in 16 24 32 48 64 128 256 512 1024; do
    sips -z $SIZE $SIZE "$BUILD_DIR/icon.png" --out "$ICONS_DIR/${SIZE}x${SIZE}.png" 2>/dev/null
    echo "   Created ${SIZE}x${SIZE}.png"
done

# Generate macOS .icns
echo "🍎 Generating macOS .icns..."
ICONSET_DIR="$BUILD_DIR/icon.iconset"
mkdir -p "$ICONSET_DIR"

# macOS iconset requires specific sizes
sips -z 16 16     "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_16x16.png" 2>/dev/null
sips -z 32 32     "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_16x16@2x.png" 2>/dev/null
sips -z 32 32     "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_32x32.png" 2>/dev/null
sips -z 64 64     "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_32x32@2x.png" 2>/dev/null
sips -z 128 128   "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_128x128.png" 2>/dev/null
sips -z 256 256   "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_128x128@2x.png" 2>/dev/null
sips -z 256 256   "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_256x256.png" 2>/dev/null
sips -z 512 512   "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_256x256@2x.png" 2>/dev/null
sips -z 512 512   "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_512x512.png" 2>/dev/null
sips -z 1024 1024 "$BUILD_DIR/icon.png" --out "$ICONSET_DIR/icon_512x512@2x.png" 2>/dev/null

# Convert iconset to icns
iconutil -c icns "$ICONSET_DIR" -o "$BUILD_DIR/icon.icns"
rm -rf "$ICONSET_DIR"
echo "✅ Created icon.icns"

# Generate Windows .ico (requires ImageMagick or we can skip and let electron-builder handle it)
if command -v convert &> /dev/null; then
    echo "🪟 Generating Windows .ico..."
    convert "$BUILD_DIR/icon.png" -define icon:auto-resize=256,128,96,64,48,32,16 "$BUILD_DIR/icon.ico"
    echo "✅ Created icon.ico"
else
    echo "⚠️  ImageMagick not found. Windows .ico will be generated by electron-builder from PNG"
    echo "   To install: brew install imagemagick"
fi

echo ""
echo "🎉 Icon generation complete!"
echo ""
echo "Generated files:"
ls -la "$BUILD_DIR"/icon.* 2>/dev/null || true
echo ""
echo "Linux icons:"
ls -la "$ICONS_DIR"/*.png 2>/dev/null || true
